language: node_js
node_js:
  - '4.2.6'
before_install:
  - npm install -g gulp
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'skip-server-render' ]; then cd .. && eval "mv $currentfolder skip-server-render" && cd skip-server-render; fi
script: gulp test
