language: node_js
node_js:
  - '4.2.6'
before_install:
  - npm install -g gulp
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-electrode-component' ]; then cd .. && eval "mv $currentfolder generator-electrode-component" && cd generator-electrode-component; fi
script: gulp test
